### ISSUE TITLE
Can't change color of `thermometer-chart`

### ISSUE THREAD

**Issue by ZeeshanAhmadKhalil** [meera/react-thermometer-chart#2]

**Comment by meera** [comment]
Fixed this issue in 1.0.3 version. 
Now you can use color as one of the properties 

Try this - 
 <Thermometer color='green' />

      <Thermometer color='blue' />

      <Thermometer color="#cc33ff" width="150px" height="240px" steps={5} minValue={1000} maxValue={40000} currentValue={20000}> 

This will produce green, blue and purple thermometer.

Please test this and let me know!

**Comment by meera** [comment]
Closing this one..

**Comment by Killaskt** [comment]
What about text color
